# Data parameters
data:
  seed: 777
  data_path: '~/.pytorch/CIFAR_data/'
  download: True
  batch_size: 8192
  shuffle: True
  drop_last: True
  download: True
  num_workers: 4
  img_size: [32, 32]

# Model parameters
model:
  input_img: [3, 32, 32]
  output_channel: 10
  num_blocks: 16

# Training parameters
train:
  epochs: 300
  lr: 0.001
  betas: [0.9, 0.999]
  eps: 0.00000001
  weight_decay: 0.01

# Save
save:
  model_name: 'cifar10'

# Other parameters
others:
  log_period: 1